In [5]:
""" 1. Create a NumPy array containing the numbers 1 to 10. Find its mean, maximum,
and minimum."""

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean = np.mean(arr)
maximum = np.max(arr)
minimum = np.min(arr)

print("Array:", arr)
print("Mean:", mean)
print("Maximum:", maximum)
print("Minimum:", minimum)

Array: [ 1  2  3  4  5  6  7  8  9 10]
Mean: 5.5
Maximum: 10
Minimum: 1


In [6]:
""" 2. Given — arr = np.array([10, 20, 30, 40, 50])
How would you:
● access the third element?
● get the first three elements?
● replace 30 with 35?"""

import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])
print(arr[:3])
arr[2] = 35
print(arr)

30
[10 20 30]
[10 20 35 40 50]


In [7]:
"""3 Create a 3 × 3 NumPy array containing numbers from 1 to 9. Find the following
● its shape
● sum of all elements
● sum of each row"""
arr = np.arange(1, 10).reshape(3, 3)

print("Array:")
print(arr)
print("Shape:", arr.shape)

print("Sum of all elements:", np.sum(arr))

print("Sum of each row:", np.sum(arr, axis=1))

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Sum of all elements: 45
Sum of each row: [ 6 15 24]


In [9]:

"""4. Given — arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) Get the following:
● The element “5” from the given array
● the last column
● the second row"""
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Element :", arr[1, 1])
print("Last column:", arr[:, -1])
print("Second row:", arr[1])

Element : 5
Last column: [3 6 9]
Second row: [4 5 6]
